name: top_ten_afghan_singer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_localization: ^0.2.1
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  wave: ^0.2.2
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  share_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/mediaLogo/
    - assets/images/singers_images/
    - assets/audios/

  # example:
  fonts:
    - family: SplashFont
      fonts:
        - asset: assets/fonts/Mikhak-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700